### ISSUE TITLE
Не совсем корректная реализация А*

### ISSUE THREAD

**Issue by RobolabGs2** [Roz1331/15-solver-java#1]
Проверка посещённых вершин в случае А* должна происходить аналогично обходу в ширину или алгоритму Дейкстры: заводим множество посещённых вершин и используем его для всех путей сразу. 

Благодаря очереди с приоритетами по наименьшему пути, при первом извлечении вершины из очереди мы оказываемся в ней наикротчайшем путём. Поэтому для эффективного отсечения недостаточно проверять, проходили ли мы в данную вершину через ту, которую собираемся добавить следующей, так как мы могли дойти по другой "ветке" более коротким путём.

```java
        // Внутри конструктора Solver
        priorityQueue.add(new ITEM(null, initial));
        // Заводим HashSet посещённых вершин
        Set<Board> visited = new HashSet<Board>();
        while (true) {
            ITEM board = priorityQueue.poll();
            // вершина может оказаться в очереди дважды,
            // так как из-за эвристики у рёбер появились веса
            if(visited.contains(board.getBoard()))
                continue;
            // поэтому же и вершину добавляем в посещённые только после извлечения из очереди
            visited.add(board.getBoard());
            // если дошли до решения, сохраняем весь путь ходов в лист
            if (board.board.isGoal()) {
                itemToList(new ITEM(board, board.board));
                return;
            }

            Iterator iterator = board.board.neighbors().iterator(); // соседи
            while (iterator.hasNext()) {
                Board board1 = (Board) iterator.next();
                // почему тут board1 может быть null? Надо такое раньше отсекать...
                // собственно, перед вставкой в очередь проверять на посещённость - правильная идея
                // только делать это лучше с помощью множества
                if(board1!=null && !visited.contains(board1))
                    priorityQueue.add(new ITEM(board, board1));
            }
        }
```

[Тут в конце](https://aimacode.github.io/aima-javascript/3-Solving-Problems-By-Searching/) есть пример А* с пошаговой анимацей, вдруг поможет чем-то.

Чтобы работал `HashSet` для `Board`, необходимо там переопределить метод `hashCode`
```java
    @Override
    public int hashCode() {
        int hash = 0;
        int size = dimension();
        for(int i = 0; i<size; i++) {
            for(int j = 0; j<size; j++) {
                hash = (hash<<2)^blocks[i][j];
            }
        }
        return hash;
    }
```

**Comment by RobolabGs2** [comment]
Так получилась какая-то помесь A* с IDA*, корректность которой ещё обосновать надо (и кажется, в случае пятнашек из-за невзвешенных рёбер, это возможно, если корректно докажешь, можно получить автомат и написать статью, если вдруг это работает всегда, то по сравнению с A* на больших объёмах получается ускорение из-за отказа от множества).

**Comment by Roz1331** [comment]
Проверка с хэшами добавлена
