### ISSUE TITLE
Слабая эвристика

### ISSUE THREAD

**Issue by RobolabGs2** [Roz1331/15-solver-java#2]
Количество фишек не на своём месте делает А* чуть лучше BFS, но эта эвристика даёт слишком мало информации.

[Манхэтанское расстояние](https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D1%81%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5_%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D1%81%D0%BA%D0%B8%D1%85_%D0%BA%D0%B2%D0%B0%D1%80%D1%82%D0%B0%D0%BB%D0%BE%D0%B2) считается почти также просто, а даёт значительный прирост: вместо секунды 27 ходов просчитываются за 21 миллисекунду, 45 ходов - за 8 секунд, 48 за 160 миллисекунд (время не прямо пропорционально глубине, да). И это улучшение происходит без каких-либо других оптимизаций.

Расстояние между двумя точками считается просто (в функцию выносить не обязательно, это для пояснения)
```
manh_dist(p1, p2) = |p1.x-p2.x|+|p1.y-p2.y|
```

Соответственно, достаточно сложить сумму расстояний для каждой фишки, (исключая пустоту), от того места, где она находится, до того места, где она должна быть.

**Comment by RobolabGs2** [comment]
Реализовать эту эвристику и пофиксить #1 достаточно для решения А* за приемлемое время.

**Comment by Roz1331** [comment]
После улучшения эвристики удалось получить следующие результаты:
```
Position 123456789ABCDEF0, Number of moves = 0, expected = 0, time = 5ms
Position 1234067859ACDEBF, Number of moves = 5, expected = 5, time = 0ms
Position 5134207896ACDEBF, Number of moves = 8, expected = 8, time = 1ms
Position 16245A3709C8DEBF, Number of moves = 10, expected = 10, time = 0ms
Position 1723068459ACDEBF, Number of moves = 13, expected = 13, time = 1ms
Position 12345678A0BE9FCD, Number of moves = 19, expected = 19, time = 10ms
Position 51247308A6BE9FCD, Number of moves = 27, expected = 27, time = 58ms
Position F2345678A0BE91DC, Number of moves = 33, expected = 33, time = 696ms
Position 75123804A6BE9FCD, Number of moves = 35, expected = 35, time = 130ms
Position 75AB2C416D389F0E, Number of moves = 45, expected = 45, time = 21727ms
Position 04582E1DF79BCA36, Number of moves = 48, expected = 48, time = 338ms
```

**Comment by RobolabGs2** [comment]
@Roz1331, можно ещё подсчёт манхэтаннского расстояния вынести в конструктор, мне кажется, пересчёт каждый раз в очереди может аффектить время (я не тестил у себя)
